[versions]
ktorClientCio = "3.4.0"
ktorClientPlugins = "3.1.1"
plugin-android = "9.0.0"
plugin-kotlin = "2.3.0"
# TODO: Update to a release once its made: https://github.com/google/ksp/issues/2743
plugin-ksp = "2.3.5-SNAPSHOT"

jecnaAPI = "9.1.0"
jecnaSupl= "1.0.3"
compose-android-bom = "2026.01.00"

composeStateEvents = "2.2.0"
composeHtml = "1.0.2"
composeCoil = "2.7.0"
accompanist = "0.37.3"
nav3Core = "1.0.0"

activity = "1.12.2"

hilt-dagger = "2.59"
hilt-android = "1.3.0"
work = "2.11.0"
datastore = "1.2.0"
serialization = "1.10.0"

[libraries]
jecnaAPI = { module = "io.github.tomhula:jecnaapi", version.ref = "jecnaAPI" }
jecnaSupl = { module = "io.github.stevekk11:jecna-supl", version.ref = "jecnaSupl" }
compose-android-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-android-bom" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
activity-compose = { module = "androidx.activity:activity-compose" }

composeStateEvents = { module = "com.github.leonard-palm:compose-state-events", version.ref = "composeStateEvents" }
composeHtml = { module = "com.github.ireward:compose-html", version.ref = "composeHtml" }
composeCoil = { module = "io.coil-kt:coil-compose", version.ref = "composeCoil" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientCio" }
ktor-client-plugins = { module = "io.ktor:ktor-client-plugins", version.ref = "ktorClientPlugins" }
navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }

activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }

hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-android" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-dagger" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-dagger" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-android" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-android" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "plugin-kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "plugin-kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "plugin-ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin-kotlin" }
legacy-kapt = { id = "com.android.legacy-kapt", version.ref = "plugin-android" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-dagger" }
