[versions]
plugin-android = "9.0.0"
plugin-kotlin = "2.3.0"
# TODO: Update to a release once its made: https://github.com/google/ksp/issues/2743
plugin-ksp = "2.3.5-SNAPSHOT"
plugin-compose = "1.10.0"
plugin-compose-hotReload = "1.0.0"

jecnaAPI = "9.1.0"

compose-android-bom = "2026.01.00"

compose = "1.10.0"
compose-materialIconsExtended = "1.7.3"
compose-material3 = "1.9.0"

composeStateEvents = "2.2.0"
composeHtml = "1.0.2"
composeCoil = "2.7.0"
accompanist = "0.37.3"
nav3Core = "1.0.0"

activity = "1.12.2"

hilt-dagger = "2.59"
hilt-android = "1.3.0"
work = "2.11.0"
datastore = "1.2.0"
serialization = "1.10.0"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"

[libraries]
jecnaAPI = { module = "io.github.tomhula:jecnaapi", version.ref = "jecnaAPI" }

compose-android-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-android-bom" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-mp = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material-icons-extended-mp = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-materialIconsExtended" }
activity-compose = { module = "androidx.activity:activity-compose" }

compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }

composeStateEvents = { module = "com.github.leonard-palm:compose-state-events", version.ref = "composeStateEvents" }
kotlinxCoroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
composeHtml = { module = "com.github.ireward:compose-html", version.ref = "composeHtml" }
composeCoil = { module = "io.coil-kt:coil-compose", version.ref = "composeCoil" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }

activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }

hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-android" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-dagger" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-dagger" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-android" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-android" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "plugin-kotlin" }
android-application = { id = "com.android.application", version.ref = "plugin-android" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "plugin-kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "plugin-compose" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "plugin-compose-hotReload" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "plugin-android" }

ksp = { id = "com.google.devtools.ksp", version.ref = "plugin-ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin-kotlin" }
legacy-kapt = { id = "com.android.legacy-kapt", version.ref = "plugin-android" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-dagger" }
